addons:
    sonarcloud:
      organization: "tylerlian"
      token:
        secure: "cf4ec5a2e7d52dcd7d1993c3db6e32ed0bdf5083" # encrypted value of your token
  
  script:
    # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
    - ant build
    - sonar-scanner