addons:
    sonarcloud:
      organization: "tylerlian"
      token:
        secure: "aa74787c84502fb9cfb5706d9592b4d97adf7d57" # encrypted value of your token
  
  script:
    # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
    - ant build
    - sonar-scanner